services:
  - type: web
    name: ds2-back
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn finanzas_back.wsgi:application"
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ds2-database
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "backendpruebas-r4zu.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://ds2-2-front.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://backendpruebas-r4zu.onrender.com"
      - key: PUBLIC_BASE_URL
        value: "https://backendpruebas-r4zu.onrender.com"
      - key: FRONTEND_BASE_URL
        value: "https://ds2-2-front.vercel.app"
      - key: DEFAULT_FROM_EMAIL
        value: "Soporte DS2 <sado56hdgm@gmail.com>"

databases:
  - name: ds2-database
    databaseName: finanzas_back_db
    user: ds2_user